### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by 06opoTeHb** [fastdatascience/faststylometry#1]
Hi. I want to try your library, but always got the same error:
Traceback (most recent call last):
  File "/stylometry/main.py", line 28, in <module>
    calculate_burrows_delta(train_corpus, test_corpus, vocab_size = 50)
  File "/stylometry/venv/lib/python3.7/site-packages/faststylometry/burrows_delta.py", line 148, in calculate_burrows_delta
    get_token_proportions(test_corpus)
  File "/stylometry/venv/lib/python3.7/site-packages/faststylometry/burrows_delta.py", line 99, in get_token_proportions
    token_proportions = corpus.df_token_counts_by_author.to_numpy() / corpus.df_total_token_counts_by_author.to_numpy()
ValueError: operands could not be broadcast together with shapes (0,51) (0,2) 

This error while running your example.
Could you check this please? 
Thanks in advance!

**Comment by Tarang** [comment]
Have the same issue

**Comment by woodthom2** [comment]
@Tarang @06opoTeHb I apologise for the issue. It was due to a dependency on an old version of Pandas which was not correcltly indicated in the setup.py. I have updated the package. Please reinstall faststylometry version 1.0.1.
